version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:   
      - '15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
    restart: always
    networks:
      - shared_network

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq-admin.localhost`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"

      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

    

networks:
  shared_network:
    external: true