services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    networks:
      - shared_network
    restart: always
    labels:
      - "traefik.enable=false" 

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - shared_network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana-admin.localhost`)"
      - "traefik.http.routers.kibana.entrypoints=web"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
  
  shop_consumer:
    build: .
    container_name: elastic_consumer
    command: >
      sh -c "python -m asyncio run elasticsearch.consumer.start_consumer"
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - shared_network
    restart: always
    labels:
      - "traefik.enable=false"

networks:
  shared_network:
    external: true
